name: Release Hackage packages
on:
  push:
    branches: [main]
    paths:
      - "**/*.cabal"
  workflow_dispatch:

jobs:
  checks:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  release-hackage-atelier-monitoring:
    uses: ./.github/workflows/release-hackage-package.yml
    needs:
      - checks
    if: ${{ !failure() && needs.checks.result == 'success' }}
    secrets: inherit
    with:
      package-name: atelier-monitoring

  release-hackage-atelier-db:
    uses: ./.github/workflows/release-hackage-package.yml
    needs:
      - checks
      - release-hackage-atelier-monitoring
    if: ${{ !failure() && needs.checks.result == 'success' }}
    secrets: inherit
    with:
      package-name: atelier-db

  release-hackage-atelier-testing:
    uses: ./.github/workflows/release-hackage-package.yml
    needs:
      - checks
      - release-hackage-atelier-db
    if: ${{ !failure() && needs.checks.result == 'success' }}
    secrets: inherit
    with:
      package-name: atelier-testing
